-- DROP TABLE IF EXISTS HDB_RENTAL_PRICE;

CREATE TABLE IF NOT EXISTS HDB_RENTAL_PRICE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RENT_APPROVAL_DATE TEXT,
    TOWN TEXT,
    BLOCK TEXT,
    STREET_NAME TEXT,
    FLAT_TYPE TEXT,
    MONTHLY_RENT FLOAT,
    UPDATE_DT TEXT
);

CREATE INDEX IF NOT EXISTS IDX_HDB_RENTAL_PRICE_RENT_APPROVAL_DATE ON HDB_RENTAL_PRICE (RENT_APPROVAL_DATE);
CREATE INDEX IF NOT EXISTS IDX_HDB_RENTAL_PRICE_TOWN ON HDB_RENTAL_PRICE (TOWN);
CREATE INDEX IF NOT EXISTS IDX_HDB_RENTAL_PRICE_BLOCK ON HDB_RENTAL_PRICE (BLOCK);
CREATE INDEX IF NOT EXISTS IDX_HDB_RENTAL_PRICE_STREET_NAME ON HDB_RENTAL_PRICE (STREET_NAME);
CREATE INDEX IF NOT EXISTS IDX_HDB_RENTAL_PRICE_FLAT_TYPE ON HDB_RENTAL_PRICE (FLAT_TYPE);
CREATE INDEX IF NOT EXISTS IDX_HDB_RENTAL_PRICE_MONTHLY_RENT ON HDB_RENTAL_PRICE (MONTHLY_RENT);
