DROP TABLE IF EXISTS HDB_ADDRESS_DETAILS;

CREATE TABLE IF NOT EXISTS HDB_ADDRESS_DETAILS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TOWN TEXT,
    STREET_NAME TEXT,
    BLK_NO TEXT,
    ROAD_NAME TEXT,
    BUILDING TEXT,
    ADDRESS TEXT,
    POSTAL TEXT,
    X FLOAT,
    Y FLOAT,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    UPDATE_DT TEXT
);

CREATE INDEX IF NOT EXISTS IDX_HDB_ADDRESS_DETAILS_ADDRESS ON HDB_ADDRESS_DETAILS (ADDRESS);
