-- DROP TABLE IF EXISTS HDB_RESALE_PRICE;

CREATE TABLE IF NOT EXISTS HDB_RESALE_PRICE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MONTH TEXT,
    TOWN TEXT,
    FLAT_TYPE TEXT,
    BLOCK TEXT,
    STREET_NAME TEXT,
    STOREY_RANGE TEXT,
    FLOOR_AREA_SQM FLOAT,
    FLAT_MODEL TEXT,
    LEASE_COMMENCE_DATE INTEGER,
    REMAINING_LEASE TEXT,
    RESALE_PRICE FLOAT,
    UPDATE_DT TEXT
);

CREATE INDEX IF NOT EXISTS IDX_HDB_RESALE_PRICE_MONTH ON HDB_RESALE_PRICE (MONTH);
CREATE INDEX IF NOT EXISTS IDX_HDB_RESALE_PRICE_TOWN ON HDB_RESALE_PRICE (TOWN);
CREATE INDEX IF NOT EXISTS IDX_HDB_RESALE_PRICE_FLAT_TYPE ON HDB_RESALE_PRICE (FLAT_TYPE);
CREATE INDEX IF NOT EXISTS IDX_HDB_RESALE_PRICE_BLOCK ON HDB_RESALE_PRICE (BLOCK);
CREATE INDEX IF NOT EXISTS IDX_HDB_RESALE_PRICE_STREET_NAME ON HDB_RESALE_PRICE (STREET_NAME);
